#!/bin/bash

function clean  {
	if [ -e "MapGen.class" ]
		then
		rm environment/*.class
		rm *.class
	fi
}
function make {
	clean
	javac *.java
}
case $@ in
	"")
	if [ -e "MapGen.class" ] 
		then java MapGen
	else
		make
		java MapGen
	fi 
	;;
	"c")
	clean
	;;
	"m")
	make
	;;
esac